muzima/muzima-android

assets/www/forms/js/muzima.js, res/values/strings.xml, res/xml/preference.xml, src/main/java/com/muzima/controller/FormController.java, src/main/java/com/muzima/view/forms/HTMLFormDataStore.java, src/main/java/com/muzima/view/forms/HTMLFormWebViewActivity.java, src/main/java/com/muzima/view/preferences/SettingsActivity.java
Added new preference under setting to allow form data duplication.
=> MUZIMA-190 : Warning when the same form data with same encounter date is  filled

src/main/java/com/muzima/view/forms/HTMLPatientJSONMapper.java
Fix to make Other Identifiers optional
=> Fix to make Other Identifiers optional

res/layout-land/activity_login.xml, res/layout/activity_login.xml, res/values/strings.xml, src/main/java/com/muzima/MuzimaApplication.java, src/main/java/com/muzima/adapters/concept/AutoCompleteBaseAdapter.java, src/main/java/com/muzima/service/MuzimaSyncService.java, src/main/java/com/muzima/view/login/LoginActivity.java, src/test/java/com/muzima/service/MuzimaSyncServiceTest.java
Please see https://github.com/muzima/muzima-api/pull/42 , this has to be merged as well.
=> MUZIMA-61 : Separate online authentication and local authentication

src/main/java/com/muzima/adapters/forms/SectionedFormsAdapter.java
Added condition to check the "view" is type of "CheckedRelativeLayout" or not before typecasting the view.
=> MUZIMA-259 : Crashing app on selecting form to delete

src/main/java/com/muzima/adapters/concept/SelectedConceptAdapter.java, src/main/java/com/muzima/adapters/concept/SelectedLocationAdapter.java, src/main/java/com/muzima/controller/ConceptController.java, src/main/java/com/muzima/controller/LocationController.java, src/main/java/com/muzima/service/MuzimaSyncService.java
This pull request fixes the static field issue that was caused by pull request for MUZIMA-57 (https://github.com/muzima/muzima-android/pull/51). So this contains the commit of MUZIMA-57 also.
=> [MUZIMA-277] Remove static field(s) in the ConceptController,LocationController and ProviderController.

AndroidManifest.xml, assets/www/forms/js/muzima.js, pom.xml, res/layout/activity_custom_provider_wizard.xml, res/layout/activity_provider_list.xml, res/layout/activity_provider_preference.xml, res/layout/item_provider_list.xml, res/raw/configuration, res/values/strings.xml, res/xml/preference.xml, src/main/java/com/muzima/MuzimaApplication.java, src/main/java/com/muzima/adapters/concept/AutoCompleteProviderAdapter.java, src/main/java/com/muzima/adapters/concept/SelectedProviderAdapter.java, src/main/java/com/muzima/controller/ProviderController.java, src/main/java/com/muzima/service/HTMLProviderParser.java, src/main/java/com/muzima/service/MuzimaSyncService.java, src/main/java/com/muzima/view/HelpActivity.java, src/main/java/com/muzima/view/cohort/CustomConceptWizardActivity.java, src/main/java/com/muzima/view/cohort/CustomProviderWizardActivity.java, src/main/java/com/muzima/view/cohort/ProviderListActivity.java, src/main/java/com/muzima/view/forms/AllAvailableFormsListFragment.java, src/main/java/com/muzima/view/forms/HTMLFormDataStore.java, src/main/java/com/muzima/view/forms/HTMLFormWebViewActivity.java, src/main/java/com/muzima/view/preferences/ProviderPreferenceActivity.java, src/main/java/com/muzima/view/preferences/SettingsActivity.java, src/test/java/com/muzima/view/forms/HTMLFormDataStoreTest.java
please marge the pull request for MUZIMA-231 in Muzima-api also. without changes of muzima-api this code will not work.
=> MUZIMA-231 : Download provider list to local repo

assets/www/forms/css/muzima.css, assets/www/forms/js/muzima.js, res/values/arrays.xml, res/values/strings.xml, res/xml/preference.xml, src/main/java/com/muzima/view/forms/HTMLFormDataStore.java, src/main/java/com/muzima/view/forms/HTMLFormWebViewActivity.java, src/main/java/com/muzima/view/preferences/SettingsActivity.java
@nribeka Please merge this pull request. There is the corresponding pull request in muzima-form (https://github.com/muzima/muzima-form/pull/24) also.
=> Muzima 280

AndroidManifest.xml, res/values/strings.xml, src/main/java/com/muzima/controller/CohortController.java, src/main/java/com/muzima/controller/ConceptController.java, src/main/java/com/muzima/controller/FormController.java, src/main/java/com/muzima/controller/LocationController.java, src/main/java/com/muzima/controller/ObservationController.java, src/main/java/com/muzima/controller/PatientController.java, src/main/java/com/muzima/controller/ProviderController.java, src/main/java/com/muzima/view/InstallBarCodeWizardActivity.java, src/main/java/com/muzima/view/MainActivity.java, src/main/java/com/muzima/view/cohort/AllCohortsListFragment.java, src/main/java/com/muzima/view/cohort/CohortWizardActivity.java, src/main/java/com/muzima/view/concept/ConceptListActivity.java, src/main/java/com/muzima/view/concept/CustomConceptWizardActivity.java, src/main/java/com/muzima/view/forms/AllAvailableFormsListFragment.java, src/main/java/com/muzima/view/forms/FormTemplateWizardActivity.java, src/main/java/com/muzima/view/location/CustomLocationWizardActivity.java, src/main/java/com/muzima/view/location/LocationListActivity.java, src/main/java/com/muzima/view/login/LoginActivity.java, src/main/java/com/muzima/view/patients/SyncPatientDataIntent.java, src/main/java/com/muzima/view/provider/CustomProviderWizardActivity.java, src/main/java/com/muzima/view/provider/ProviderListActivity.java
Clear data from the previous run of the wizard, if the wizard crashes or is interrupted.
=> Muzima 289

assets/www/forms/js/muzima.js
I am not able to keep both muzima.js files in sync. Sorry for the delay.
=> MUZIMA-268 - Applying validation and autocompletion on consultant field

src/main/java/com/muzima/service/HTMLFormObservationCreator.java
This fix the issue filed under LARK-22
=> LARK-22: Fix NullPointerException issue incase of null observation value

src/main/java/com/muzima/MuzimaApplication.java, src/main/java/com/muzima/adapters/ListAdapter.java, src/main/java/com/muzima/adapters/patients/PatientAdapterHelper.java, src/main/java/com/muzima/adapters/patients/PatientsRemoteSearchAdapter.java, src/main/java/com/muzima/service/MuzimaSyncService.java, src/main/java/com/muzima/utils/Constants.java, src/main/java/com/muzima/view/BroadcastListenerActivity.java, src/main/java/com/muzima/view/cohort/AllCohortsListFragment.java, src/main/java/com/muzima/view/cohort/CohortActivity.java, src/main/java/com/muzima/view/cohort/CohortListFragment.java, src/main/java/com/muzima/view/cohort/CohortWizardActivity.java, src/main/java/com/muzima/view/encounters/EncounterSummaryActivity.java, src/main/java/com/muzima/view/encounters/EncountersActivity.java, src/main/java/com/muzima/view/forms/AllAvailableFormsListFragment.java, src/main/java/com/muzima/view/forms/FormTemplateWizardActivity.java, src/main/java/com/muzima/view/forms/FormsActivity.java, src/main/java/com/muzima/view/forms/FormsListFragment.java, src/main/java/com/muzima/view/login/LoginActivity.java, src/main/java/com/muzima/view/notifications/NotificationListFragment.java, src/main/java/com/muzima/view/notifications/NotificationsListActivity.java, src/main/java/com/muzima/view/observations/ObservationByEncountersFragment.java, src/main/java/com/muzima/view/observations/ObservationsByConceptFragment.java, src/main/java/com/muzima/view/patients/PatientRemoteSearchListActivity.java, src/main/java/com/muzima/view/patients/PatientsListActivity.java, src/main/res/layout/activity_patient_remote_search_list.xml, src/main/res/menu/download_form_template_wizard.xml, src/main/res/menu/form_list_menu.xml, src/main/res/values/strings.xml
Improve network diagnostics during patient search, and display appropriate error message when applicable
=> MUZIMA-354

app/src/main/java/com/muzima/service/MuzimaSyncService.java, app/src/main/java/com/muzima/view/patients/PatientsListActivity.java, app/src/main/res/layout/activity_cohort_wizard.xml, app/src/main/res/layout/activity_custom_concept_wizard.xml, app/src/main/res/layout/activity_custom_location_wizard.xml, app/src/main/res/layout/activity_custom_provider_wizard.xml, app/src/main/res/layout/activity_guided_setup_wizard.xml, app/src/main/res/layout/activity_install_barcode_wizard.xml, app/src/main/res/layout/activity_setup_method_wizard.xml, app/src/main/res/menu/client_list.xml, app/src/main/res/values/styles.xml
=> Muzima 467

app/src/main/java/com/muzima/view/patients/PatientsListActivity.java
MUZIMA-562 Fixed Potential UI issue, with new patient/existing patient first card scanning scenarios
=> MUZIMA-562 Fixed Potential UI issue, with new patient/existing 

app/build.gradle, app/src/main/assets/www/forms/js/muzima.js, app/src/main/res/values/strings.xml
Unfortunately, forgot to push last minute changes, for the previous PR. 
Changes address issues raised in code review.
=> Post Merge Refactor Muzima GPS Data

app/src/main/java/com/muzima/view/preferences/settings/SettingsPreferenceFragment.java, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values-sw/strings.xml, app/src/main/res/values/strings.xml
I have branched off from an old version, because the I couldn't build the latest version.  The publicly available  muzima-api v1.1.4 jar doesn't contain some newly introduced GPS constants.
=> MUZIMA-653: mUzima session timeout valiation

app/src/main/res/xml/preference.xml
I set the 'selectAllOnFocus' property for form save intervall editTextPreference
=> MUZIMA-667:Reposition cursor on automatic form save interval

app/src/main/java/com/muzima/view/preferences/settings/SettingsPreferenceFragment.java
According to the test results, I modified the session timeout validation, so it will check the empty values
=> MUZIMA-653: mUzima session timeout validation

app/src/main/java/com/muzima/view/InteractiveHelpActivity.java
Hello @benamonya, I fixed the app crash problem was found on Friday. (It was caused by calling String.join method which is a Java 8 method). Please check my modification. Thanks.
=> MUZIMA-688: change string concatenation for avoiding app crash

app/src/main/java/com/muzima/view/preferences/settings/SettingsPreferenceFragment.java, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values-sw/strings.xml, app/src/main/res/values/strings.xml
Hello @benamonya, I made the modification. Please check the code. Thanks!
=> MUZIMA-738:Automatic form save interval accepts a blank input

app/src/main/java/com/muzima/controller/MuzimaSettingController.java, app/src/main/java/com/muzima/view/patients/PatientSummaryActivity.java, app/src/main/res/layout/activity_client_summary.xml
Reverts muzima/muzima-android#229
=> Revert "Clinical Summary enabling/disabling depending on setting"

app/src/main/java/com/muzima/service/DataSyncService.java, app/src/main/java/com/muzima/view/relationship/RelationshipsListActivity.java, app/src/main/java/com/muzima/view/setupconfiguration/GuidedConfigurationWizardActivity.java
=>  Muzima-837

app/src/main/java/com/muzima/view/patients/PatientsListActivity.java, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values-sw/strings.xml, app/src/main/res/values/strings.xml
=> MUZIMA-697

app/src/main/res/layout/activity_client_summary.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-gu/strings.xml, app/src/main/res/values-hi/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values-sw/strings.xml, app/src/main/res/values/strings.xml
Apply translation to muzima code at commit 2b47a478
=> MUZIMA-861

app/src/main/java/com/muzima/MuzimaApplication.java, app/src/main/java/com/muzima/utils/MuzimaPreferenceUtils.java, app/src/main/java/com/muzima/view/BaseFragmentActivity.java, app/src/main/java/com/muzima/view/BroadcastListenerActivity.java, app/src/main/java/com/muzima/view/DefaultMenuDropDownHelper.java, app/src/main/java/com/muzima/view/MainActivity.java, app/src/main/java/com/muzima/view/login/LoginActivity.java, app/src/main/java/com/muzima/view/preferences/CohortPreferenceActivity.java, app/src/main/java/com/muzima/view/preferences/MuzimaTimer.java, app/src/main/java/com/muzima/view/preferences/SettingsActivity.java
=> MUZIMA-596

app/build.gradle, app/src/main/java/com/muzima/MuzimaApplication.java, app/src/main/java/com/muzima/controller/CohortController.java, app/src/main/java/com/muzima/controller/EncounterController.java, app/src/main/java/com/muzima/controller/MuzimaSettingController.java, app/src/main/java/com/muzima/controller/PersonController.java, app/src/main/java/com/muzima/controller/RelationshipController.java, app/src/main/java/com/muzima/service/MuzimaSyncService.java, app/src/main/java/com/muzima/service/OnlineOnlyModePreferenceService.java, app/src/main/java/com/muzima/view/initialwizard/GuidedConfigurationWizardActivity.java, app/src/main/java/com/muzima/view/login/LoginActivity.java, app/src/main/java/com/muzima/view/preferences/settings/SettingsPreferenceFragment.java, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-gu/strings.xml, app/src/main/res/values-hi/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values-sw/strings.xml, app/src/main/res/values/keys.xml, app/src/main/res/values/strings.xml
This is the parent PR for Online only mode feature
=> Muzima 872

app/src/main/res/values-pt/strings.xml
Replace "Clientes" by "Utentes" in all UI's
=> Replacing 'Cliente' by 'Utente'

app/src/main/java/com/muzima/adapters/patients/PatientAdapterHelper.java, app/src/main/java/com/muzima/adapters/relationships/RelationshipsAdapter.java, app/src/main/java/com/muzima/view/forms/FormsWithDataActivity.java, app/src/main/java/com/muzima/view/patients/DataCollectionActivity.java, app/src/main/java/com/muzima/view/patients/ObsViewActivity.java, app/src/main/java/com/muzima/view/patients/PatientSummaryActivity.java, app/src/main/java/com/muzima/view/relationship/RelationshipsListActivity.java, app/src/main/java/com/muzima/view/reports/PatientReportActivity.java, app/src/main/res/layout/activity_client_summary.xml, app/src/main/res/layout/client_summary_patients_list.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values/strings.xml
HV_006 - View Cohort Patient List - Solving issues
=> HV_006_View_Patient_List

app/src/main/java/com/muzima/view/patients/PatientSummaryActivity.java
Updating uuid of the derived concept of Latest Volunteer who made successful visit
=> Updating uuid of the derived concept of Latest Volunteer who made successful visit

app/src/main/java/com/muzima/view/forms/HTMLFormDataStore.java
Filtering only interventions derived concepts
=> Filtering only interventions derived concepts

app/src/main/java/com/muzima/tasks/LoadDownloadedCohortsTask.java
Displaying the derived concept name even if it has no patients
=> Displaying the derived concept name even if it has no patients
